#hello deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-application-deployment
  namespace: tiacourses
  labels:
    app: flask-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-application
  template:
    metadata:
      labels:
        app: flask-application
    spec:
      containers:
      - name: flask-application
        image: lloyddigital/flask-app:latest  # Replace this with the name of your Docker image
        ports:
        - containerPort: 2024
        resources:
          limits:
            cpu: "800m"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

---
apiVersion: v1
kind: Service
metadata:
  name: flask-application-svc
  namespace: tiacourses
  labels:
    app: flask-application
spec:
  selector:
    app: flask-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2024

