apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-application-deployment
  namespace: tiacourses
  labels:
    app: python-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-application
  template:
    metadata:
      labels:
        app: python-application
    spec:
      containers:
      - name: python-application
        image: lloyddigital/web-app:latest  #Docker image
        imagePullPolicy: Always
        ports:
        - containerPort: 2024
          protocol: TCP
        stdin: true
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "100Mi"
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

---
apiVersion: v1
kind: Service
metadata:
  name: python-application-svc
  namespace: tiacourses
  labels:
    app: python-application
spec:
  selector:
    app: python-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2024
  type: ClusterIP