apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deploy
  namespace: tiacourses
  labels:
    app: python-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-application
  template:
    metadata:
      labels:
        app: python-application
    spec:
      containers:
      - name: python-application
        image: python-app:$TAG  # Replace this with the name of your Docker image
        imagePullPolicy: Always
        ports:
        - containerPort: 2024
        resources:
          limits:
            cpu: "100m"
            memory: "100Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

---
apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
  namespace: tiacourses
  labels:
    app: python-application
spec:
  selector:
    app: python-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2024
  type: ClusterIP
